// Generated automatically from AgendaFest.xlsx by sync_excel.cjs
// Do not edit this file manually.

export interface ArtistSocialLinks {
  officialWebsite?: string;
  tiktokUrl?: string;
  xUrl?: string;
}

const artistSocialLinks: Record<string, ArtistSocialLinks> = {
  "annisokay": {
    "officialWebsite": "https://www.annisokay.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/annisokay"
  },
  "sabaton": {
    "officialWebsite": "https://www.sabaton.net/",
    "tiktokUrl": "https://www.tiktok.com/@sabaton",
    "xUrl": "https://twitter.com/sabaton"
  },
  "psychonaut": {
    "officialWebsite": "https://psychonautband.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/psychonautband"
  },
  "feuerschwanz": {
    "officialWebsite": "https://www.feuerschwanz.de/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/metundmiezen"
  },
  "creeper": {
    "officialWebsite": "https://creepercult.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/creepercult"
  },
  "northlane": {
    "officialWebsite": "https://northlaneband.com/",
    "tiktokUrl": "https://www.tiktok.com/@northlane",
    "xUrl": "https://x.com/northlane"
  },
  "godsmack": {
    "officialWebsite": "https://godsmack.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/godsmack"
  },
  "deicide": {
    "officialWebsite": "",
    "tiktokUrl": "",
    "xUrl": "https://x.com/deicideband"
  },
  "helloween": {
    "officialWebsite": "https://www.helloween.org/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/helloween"
  },
  "crowbar": {
    "officialWebsite": "https://crowbarmusic.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/crowbarmusic"
  },
  "heavenshallburn": {
    "officialWebsite": "https://www.heavenshallburn.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/hsb_official"
  },
  "implantpentrurefuz": {
    "officialWebsite": "https://www.implantpentrurefuz.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/IPRMusicBand"
  },
  "blacklabelsociety": {
    "officialWebsite": "https://blacklabelsociety.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/ZakkWyldeBLS"
  },
  "marilynmanson": {
    "officialWebsite": "https://marilynmanson.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/marilynmanson"
  },
  "necrotted": {
    "officialWebsite": "https://necrotted.com/",
    "tiktokUrl": "",
    "xUrl": ""
  },
  "panzerfaust": {
    "officialWebsite": "https://panzerfaust.bandcamp.com",
    "tiktokUrl": "",
    "xUrl": ""
  },
  "hackneyed": {
    "officialWebsite": "http://www.hackneyed.de/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/hackneyedband"
  },
  "vended": {
    "officialWebsite": "https://officialvended.com/",
    "tiktokUrl": "https://www.tiktok.com/@vended_official",
    "xUrl": "https://x.com/vendedofficial"
  },
  "majestica": {
    "officialWebsite": "https://majestica.nu/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/majesticametal"
  },
  "alcest": {
    "officialWebsite": "https://alcest-music.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/alcestofficial"
  },
  "deathangel": {
    "officialWebsite": "https://www.deathangel.us/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/deathangel"
  },
  "fumanchu": {
    "officialWebsite": "https://fu-manchu.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/fumanchuband"
  },
  "elder": {
    "officialWebsite": "https://beholdtheelder.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/elder_band"
  },
  "bleedfromwithin": {
    "officialWebsite": "https://bleedfromwithin.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/bleedfromwithin"
  },
  "igorrr": {
    "officialWebsite": "https://igorrr.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/igorrr"
  },
  "hatebreed": {
    "officialWebsite": "https://hatebreed.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/hatebreed"
  },
  "gutalax": {
    "officialWebsite": "https://bandzone.cz/gutalax?at=info",
    "tiktokUrl": "",
    "xUrl": "https://x.com/GutalaxGore"
  },
  "orbitculture": {
    "officialWebsite": "https://orbitculture.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/orbitculture"
  },
  "nevermore": {
    "officialWebsite": "http://www.nevermore.tv",
    "tiktokUrl": "",
    "xUrl": "https://x.com/nevermoreband"
  },
  "inflames": {
    "officialWebsite": "https://www.inflames.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/InFlames_SWE"
  },
  "employedtoserve": {
    "officialWebsite": "https://www.employedtoserve.com/",
    "tiktokUrl": "https://www.tiktok.com/@employedtoserve",
    "xUrl": "https://twitter.com/employedtoserve"
  },
  "tribulation": {
    "officialWebsite": "https://www.tribulation.se/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/TribulationBand"
  },
  "cryptopsy": {
    "officialWebsite": "http://www.myspace.com/cryptopsy",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/Cryptopsy"
  },
  "nonestdeus": {
    "officialWebsite": "https://noisebringer.de/index.php/de/projekte/non-est-deus",
    "tiktokUrl": "",
    "xUrl": ""
  },
  "immolation": {
    "officialWebsite": "https://www.everlastingfire.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/immolation"
  },
  "deafheaven": {
    "officialWebsite": "https://deafheaven.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/deafheavenband"
  },
  "grave": {
    "officialWebsite": "https://www.grave.se/",
    "tiktokUrl": "",
    "xUrl": ""
  },
  "allt": {
    "officialWebsite": "https://www.alltband.com/",
    "tiktokUrl": "https://www.tiktok.com/@alltband",
    "xUrl": "https://twitter.com/alltband"
  },
  "municipalwaste": {
    "officialWebsite": "https://www.municipalwaste.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/municipalwaste"
  },
  "inextremo": {
    "officialWebsite": "https://www.inextremo.de/",
    "tiktokUrl": "",
    "xUrl": ""
  },
  "archenemy": {
    "officialWebsite": "https://www.archenemy.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/archenemy"
  },
  "lambofgod": {
    "officialWebsite": "https://www.lamb-of-god.com/",
    "tiktokUrl": "https://www.tiktok.com/@lambofgod",
    "xUrl": "https://x.com/lambofgod"
  },
  "vader": {
    "officialWebsite": "https://vader.pl/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/vaderband"
  },
  "thyartismurder": {
    "officialWebsite": "https://www.thyartismurder.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/thyartismurder"
  },
  "accept": {
    "officialWebsite": "https://www.acceptworldwide.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/accepttheband"
  },
  "slaughtertoprevail": {
    "officialWebsite": "https://slaughtertoprevail.com/",
    "tiktokUrl": "https://www.tiktok.com/@slaughtertoprevail",
    "xUrl": ""
  },
  "novembersdoom": {
    "officialWebsite": "https://www.novembersdoom.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/novembersdoom"
  },
  "animalsasleaders": {
    "officialWebsite": "https://www.animalsasleaders.org/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/animalsasleaders"
  },
  "theghostinside": {
    "officialWebsite": "https://www.theghostinside.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/theghostinside"
  },
  "perturbator": {
    "officialWebsite": "https://perturbator.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/Perturbator"
  },
  "candlemass": {
    "officialWebsite": "https://www.candlemass.se/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/candlemass"
  },
  "raisedbyowls": {
    "officialWebsite": "https://raisedbyowls.bigcartel.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/raisedbyowls"
  },
  "fitforanautopsy": {
    "officialWebsite": "https://fitforanautopsy.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/fitforanautopsy"
  },
  "trooper": {
    "officialWebsite": "https://trooper.ro/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/Trooper_Salute"
  },
  "satyricon": {
    "officialWebsite": "https://www.satyricon.no/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/Satyricon"
  },
  "cripplingalcoholism": {
    "officialWebsite": "",
    "tiktokUrl": "https://www.tiktok.com/@your.crippling.alcoholism",
    "xUrl": "https://twitter.com/Crippling_Alc"
  },
  "serrabulho": {
    "officialWebsite": "http://www.serrabulho.com/",
    "tiktokUrl": "https://www.tiktok.com/@serrabulhogrind",
    "xUrl": "https://twitter.com/serrabulhogrind"
  },
  "airbourne": {
    "officialWebsite": "https://airbourneairbourne.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/airbourne"
  },
  "amorphis": {
    "officialWebsite": "https://amorphis.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/amorphis"
  },
  "machukha": {
    "officialWebsite": "",
    "tiktokUrl": "https://www.tiktok.com/@machakaunique",
    "xUrl": ""
  },
  "slowcrush": {
    "officialWebsite": "https://slowcrush.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/slowcrushband"
  },
  "conservativemilitaryimage": {
    "officialWebsite": "https://www.conservativemilitaryimage.com/",
    "tiktokUrl": "",
    "xUrl": ""
  },
  "monolord": {
    "officialWebsite": "https://monolord.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/monolordofficial"
  },
  "bucovina": {
    "officialWebsite": "https://bucovina.band/",
    "tiktokUrl": "",
    "xUrl": ""
  },
  "malevolence": {
    "officialWebsite": "https://mlvst.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/malevolenceriff"
  },
  "alexandracapitanescu": {
    "officialWebsite": "",
    "tiktokUrl": "https://www.tiktok.com/@alexoi.capi",
    "xUrl": ""
  },
  "coroner": {
    "officialWebsite": "https://coroner-band.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/coronerband"
  },
  "wolvesinthethroneroom": {
    "officialWebsite": "https://wittr.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/wittrofficial"
  },
  "decapitated": {
    "officialWebsite": "https://www.decapitatedband.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/decapitated"
  },
  "periphery": {
    "officialWebsite": "https://periphery.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/peripheryband"
  },
  "grandson": {
    "officialWebsite": "https://www.grandsonmusic.com/",
    "tiktokUrl": "https://www.tiktok.com/@grandson",
    "xUrl": "https://x.com/grandson"
  },
  "theprodigy": {
    "officialWebsite": "https://theprodigy.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/the_prodigy"
  },
  "signsoftheswarm": {
    "officialWebsite": "https://signsoftheswarm.com/",
    "tiktokUrl": "https://www.tiktok.com/@signsoftheswarmofficial",
    "xUrl": "https://x.com/signsoftheswarm"
  },
  "carcass": {
    "officialWebsite": "https://www.reekofcarcass.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/CarcassBand"
  },
  "thegathering": {
    "officialWebsite": "https://www.gathering.nl/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/TheGatheringBand"
  },
  "soulfly": {
    "officialWebsite": "https://www.soulfly.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/TheSoulflyTribe"
  },
  "heavyhitter": {
    "officialWebsite": "",
    "tiktokUrl": "https://www.tiktok.com/@heavyhitterfl",
    "xUrl": "https://twitter.com/heavyhitterfl"
  },
  "voivod": {
    "officialWebsite": "https://voivod.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/voivoddotnet"
  },
  "evergrey": {
    "officialWebsite": "https://evergrey.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/evergrey"
  },
  "insomnium": {
    "officialWebsite": "https://insomnium.net/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/insomniumband"
  },
  "sventevith": {
    "officialWebsite": "http://www.cocoon.net/svenvath",
    "tiktokUrl": "",
    "xUrl": "https://x.com/svenvaeth"
  }
};

function normalizeArtistName(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

export function getArtistSocialLinks(name: string): ArtistSocialLinks {
  return artistSocialLinks[normalizeArtistName(name)] || {};
}
