// Generated automatically from AgendaFest.xlsx by sync_excel.cjs
// Do not edit this file manually.

export interface ArtistSocialLinks {
  officialWebsite?: string;
  tiktokUrl?: string;
  xUrl?: string;
}

const artistSocialLinks: Record<string, ArtistSocialLinks> = {
  "annisokay": {
    "officialWebsite": "https://www.annisokay.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/annisokay"
  },
  "sabaton": {
    "officialWebsite": "https://www.sabaton.net/",
    "tiktokUrl": "https://www.tiktok.com/@sabaton",
    "xUrl": "https://twitter.com/sabaton"
  },
  "psychonaut": {
    "officialWebsite": "https://psychonautband.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/psychonautband"
  },
  "feuerschwanz": {
    "officialWebsite": "https://www.feuerschwanz.de/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/metundmiezen"
  },
  "gaerea": {
    "officialWebsite": "https://www.gaerea.com/",
    "tiktokUrl": "https://www.tiktok.com/@gaereaofficial",
    "xUrl": "https://twitter.com/gaerea_official"
  },
  "hamlet": {
    "officialWebsite": "http://www.hamlet1.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/Hamlet_Band"
  },
  "creeper": {
    "officialWebsite": "https://creepercult.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/creepercult"
  },
  "northlane": {
    "officialWebsite": "https://northlaneband.com/",
    "tiktokUrl": "https://www.tiktok.com/@northlane",
    "xUrl": "https://x.com/northlane"
  },
  "godsmack": {
    "officialWebsite": "https://godsmack.com/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/godsmack"
  },
  "deicide": {
    "officialWebsite": "",
    "tiktokUrl": "",
    "xUrl": "https://x.com/deicideband"
  },
  "helloween": {
    "officialWebsite": "https://www.helloween.org/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/helloween"
  },
  "therealmckenzies": {
    "officialWebsite": "http://therealmckenzies.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/RealMcKenzies"
  },
  "ruxeruxe": {
    "officialWebsite": "http://www.ruxeruxe.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/RuxeRuxe"
  },
  "ochobre": {
    "officialWebsite": "https://ochobre.es/",
    "tiktokUrl": "",
    "xUrl": ""
  },
  "hermanafuria": {
    "officialWebsite": "https://hermanafuria.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/hermanafuria"
  },
  "eldrogas": {
    "officialWebsite": "https://eldrogas.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/eldrogas"
  },
  "benitokamelas": {
    "officialWebsite": "https://benitokamelas.es/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/benitokamelas"
  },
  "thelizards": {
    "officialWebsite": "https://thelizards.bandcamp.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/TheLizardsBCN"
  },
  "reversethemoment": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "crowbar": {
    "officialWebsite": "https://crowbarmusic.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/crowbarmusic"
  },
  "heavenshallburn": {
    "officialWebsite": "https://www.heavenshallburn.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/hsb_official"
  },
  "implantpentrurefuz": {
    "officialWebsite": "https://www.implantpentrurefuz.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/IPRMusicBand"
  },
  "blacklabelsociety": {
    "officialWebsite": "https://blacklabelsociety.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/ZakkWyldeBLS"
  },
  "marilynmanson": {
    "officialWebsite": "https://marilynmanson.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/marilynmanson"
  },
  "necrotted": {
    "officialWebsite": "https://necrotted.com/",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "panzerfaust": {
    "officialWebsite": "https://panzerfaust.bandcamp.com",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "hackneyed": {
    "officialWebsite": "http://www.hackneyed.de/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/hackneyedband"
  },
  "vended": {
    "officialWebsite": "https://officialvended.com/",
    "tiktokUrl": "https://www.tiktok.com/@vended_official",
    "xUrl": "https://x.com/vendedofficial"
  },
  "majestica": {
    "officialWebsite": "https://majestica.nu/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/majesticametal"
  },
  "alcest": {
    "officialWebsite": "https://alcest-music.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/alcestofficial"
  },
  "deathangel": {
    "officialWebsite": "https://www.deathangel.us/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/deathangel"
  },
  "fumanchu": {
    "officialWebsite": "https://fu-manchu.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/fumanchuband"
  },
  "elder": {
    "officialWebsite": "https://beholdtheelder.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/elder_band"
  },
  "bleedfromwithin": {
    "officialWebsite": "https://bleedfromwithin.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/bleedfromwithin"
  },
  "igorrr": {
    "officialWebsite": "https://igorrr.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/igorrr"
  },
  "hatebreed": {
    "officialWebsite": "https://hatebreed.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/hatebreed"
  },
  "rotheads": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "gutalax": {
    "officialWebsite": "https://bandzone.cz/gutalax?at=info",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/GutalaxGore"
  },
  "orbitculture": {
    "officialWebsite": "https://orbitculture.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/orbitculture"
  },
  "nevermore": {
    "officialWebsite": "http://www.nevermore.tv",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/nevermoreband"
  },
  "inflames": {
    "officialWebsite": "https://www.inflames.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/InFlames_SWE"
  },
  "employedtoserve": {
    "officialWebsite": "https://www.employedtoserve.com/",
    "tiktokUrl": "https://www.tiktok.com/@employedtoserve",
    "xUrl": "https://twitter.com/employedtoserve"
  },
  "tribulation": {
    "officialWebsite": "https://www.tribulation.se/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/TribulationBand"
  },
  "cryptopsy": {
    "officialWebsite": "http://www.myspace.com/cryptopsy",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/Cryptopsy"
  },
  "nonestdeus": {
    "officialWebsite": "https://noisebringer.de/index.php/de/projekte/non-est-deus",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "immolation": {
    "officialWebsite": "https://www.everlastingfire.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/immolation"
  },
  "deafheaven": {
    "officialWebsite": "https://deafheaven.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/deafheavenband"
  },
  "grave": {
    "officialWebsite": "https://www.grave.se/",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "allt": {
    "officialWebsite": "https://www.alltband.com/",
    "tiktokUrl": "https://www.tiktok.com/@alltband",
    "xUrl": "https://twitter.com/alltband"
  },
  "municipalwaste": {
    "officialWebsite": "https://www.municipalwaste.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/municipalwaste"
  },
  "inextremo": {
    "officialWebsite": "https://www.inextremo.de/",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "archenemy": {
    "officialWebsite": "https://www.archenemy.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/archenemy"
  },
  "lambofgod": {
    "officialWebsite": "https://www.lamb-of-god.com/",
    "tiktokUrl": "https://www.tiktok.com/@lambofgod",
    "xUrl": "https://x.com/lambofgod"
  },
  "underwaves": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "vader": {
    "officialWebsite": "https://vader.pl/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/vaderband"
  },
  "thyartismurder": {
    "officialWebsite": "https://www.thyartismurder.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/thyartismurder"
  },
  "accept": {
    "officialWebsite": "https://www.acceptworldwide.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/accepttheband"
  },
  "slaughtertoprevail": {
    "officialWebsite": "https://slaughtertoprevail.com/",
    "tiktokUrl": "https://www.tiktok.com/@slaughtertoprevail",
    "xUrl": "124"
  },
  "novembersdoom": {
    "officialWebsite": "https://www.novembersdoom.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/novembersdoom"
  },
  "animalsasleaders": {
    "officialWebsite": "https://www.animalsasleaders.org/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/animalsasleaders"
  },
  "theghostinside": {
    "officialWebsite": "https://www.theghostinside.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/theghostinside"
  },
  "perturbator": {
    "officialWebsite": "https://perturbator.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/Perturbator"
  },
  "candlemass": {
    "officialWebsite": "https://www.candlemass.se/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/candlemass"
  },
  "raisedbyowls": {
    "officialWebsite": "https://raisedbyowls.bigcartel.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/raisedbyowls"
  },
  "fitforanautopsy": {
    "officialWebsite": "https://fitforanautopsy.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/fitforanautopsy"
  },
  "trooper": {
    "officialWebsite": "https://trooper.ro/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/Trooper_Salute"
  },
  "satyricon": {
    "officialWebsite": "https://www.satyricon.no/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/Satyricon"
  },
  "cripplingalcoholism": {
    "officialWebsite": "124",
    "tiktokUrl": "https://www.tiktok.com/@your.crippling.alcoholism",
    "xUrl": "https://twitter.com/Crippling_Alc"
  },
  "serrabulho": {
    "officialWebsite": "http://www.serrabulho.com/",
    "tiktokUrl": "https://www.tiktok.com/@serrabulhogrind",
    "xUrl": "https://twitter.com/serrabulhogrind"
  },
  "airbourne": {
    "officialWebsite": "https://airbourneairbourne.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/airbourne"
  },
  "amorphis": {
    "officialWebsite": "https://amorphis.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/amorphis"
  },
  "machukha": {
    "officialWebsite": "124",
    "tiktokUrl": "https://www.tiktok.com/@machakaunique",
    "xUrl": "124"
  },
  "slowcrush": {
    "officialWebsite": "https://slowcrush.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/slowcrushband"
  },
  "conservativemilitaryimage": {
    "officialWebsite": "https://www.conservativemilitaryimage.com/",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "monolord": {
    "officialWebsite": "https://monolord.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/monolordofficial"
  },
  "bucovina": {
    "officialWebsite": "https://bucovina.band/",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "malevolence": {
    "officialWebsite": "https://mlvst.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/malevolenceriff"
  },
  "alexandracapitanescu": {
    "officialWebsite": "124",
    "tiktokUrl": "https://www.tiktok.com/@alexoi.capi",
    "xUrl": "124"
  },
  "coroner": {
    "officialWebsite": "https://coroner-band.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/coronerband"
  },
  "wolvesinthethroneroom": {
    "officialWebsite": "https://wittr.com/",
    "tiktokUrl": "124",
    "xUrl": "https://twitter.com/wittrofficial"
  },
  "parnaie": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "decapitated": {
    "officialWebsite": "https://www.decapitatedband.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/decapitated"
  },
  "periphery": {
    "officialWebsite": "https://periphery.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/peripheryband"
  },
  "grandson": {
    "officialWebsite": "https://www.grandsonmusic.com/",
    "tiktokUrl": "https://www.tiktok.com/@grandson",
    "xUrl": "https://x.com/grandson"
  },
  "theprodigy": {
    "officialWebsite": "https://theprodigy.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/the_prodigy"
  },
  "signsoftheswarm": {
    "officialWebsite": "https://signsoftheswarm.com/",
    "tiktokUrl": "https://www.tiktok.com/@signsoftheswarmofficial",
    "xUrl": "https://x.com/signsoftheswarm"
  },
  "carcass": {
    "officialWebsite": "https://www.reekofcarcass.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/CarcassBand"
  },
  "thegathering": {
    "officialWebsite": "https://www.gathering.nl/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/TheGatheringBand"
  },
  "soulfly": {
    "officialWebsite": "https://www.soulfly.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/TheSoulflyTribe"
  },
  "heavyhitter": {
    "officialWebsite": "124",
    "tiktokUrl": "https://www.tiktok.com/@heavyhitterfl",
    "xUrl": "https://twitter.com/heavyhitterfl"
  },
  "voivod": {
    "officialWebsite": "https://voivod.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/voivoddotnet"
  },
  "evergrey": {
    "officialWebsite": "https://evergrey.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/evergrey"
  },
  "lefttodie": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "hvnds": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "insomnium": {
    "officialWebsite": "https://insomnium.net/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/insomniumband"
  },
  "sventevith": {
    "officialWebsite": "http://www.cocoon.net/svenvath",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/svenvaeth"
  },
  "dakidarria": {
    "officialWebsite": "https://dakidarria.gal/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/dakidarria"
  },
  "soziedadalkoholika": {
    "officialWebsite": "https://www.soziedadalkoholika.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/soziedadalk"
  },
  "thetoydolls": {
    "officialWebsite": "https://thetoydolls.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/thetoydolls"
  },
  "reincidentes": {
    "officialWebsite": "https://reincidentes.info/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/reincidentes"
  },
  "eukz": {
    "officialWebsite": "https://eukz.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/eukz_oficial"
  },
  "sonsofaguirrescila": {
    "officialWebsite": "https://sonsofaguirre.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/sonsofaguirre"
  },
  "sinkope": {
    "officialWebsite": "https://sinkope.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/sinkope_oficial"
  },
  "parabellum": {
    "officialWebsite": "https://parabellum.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/parabellum_ofic"
  },
  "gritandoensilencio": {
    "officialWebsite": "https://gritandoensilencio.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/gritando_rock"
  },
  "pedra": {
    "officialWebsite": "http://www.extremoduro.com",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/_extremoduro"
  },
  "deafdevils": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "ratzinger": {
    "officialWebsite": "https://ratzinger.band/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/ratzinger_oficial"
  },
  "ktulu": {
    "officialWebsite": "https://ktulu.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/ktulu_oficial"
  },
  "bihotza": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "ebriknight": {
    "officialWebsite": "https://ebriknight.cat/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/ebriknight"
  },
  "trastiendarc": {
    "officialWebsite": "124",
    "tiktokUrl": "https://www.tiktok.com/@trastienda.rc.ofi",
    "xUrl": "https://x.com/TrastiendaRC"
  },
  "desastre": {
    "officialWebsite": "https://desastre.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/desastreoficial"
  },
  "lauradsk": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "thebirrasterror": {
    "officialWebsite": "https://thebirrasterror.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/birrasterror"
  },
  "evaristo": {
    "officialWebsite": "http://www.lapollarecords.net/",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "narco": {
    "officialWebsite": "https://narco.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/narco_oficial"
  },
  "talco": {
    "officialWebsite": "https://talco.punkchanka.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/talcopunkchanka"
  },
  "porretas": {
    "officialWebsite": "https://porretas.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/porretasoficial"
  },
  "josetxupiperrak": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "envidiakotxina": {
    "officialWebsite": "https://envidiakotxina.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/envidiakotxina"
  },
  "kaosetiliko": {
    "officialWebsite": "https://kaosetiliko.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/kaosetiliko"
  },
  "manifa": {
    "officialWebsite": "https://manifa.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/manifapunk"
  },
  "manolokabezabolo": {
    "officialWebsite": "https://manolokabezabolo.com/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/manolokabezabol"
  },
  "arpaviejas": {
    "officialWebsite": "https://arpaviejas.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/arpaviejas"
  },
  "periferia": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "distorsion": {
    "officialWebsite": "https://distorsion.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/distorsionpunk"
  },
  "iratxo": {
    "officialWebsite": "https://iratxo.es/",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/iratxo_oficial"
  },
  "lonchavelasco": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "malosvicios": {
    "officialWebsite": "https://malosvicios.com",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "malditomatas": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "groggyrude": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "lapegatina": {
    "officialWebsite": "https://lapegatina.com",
    "tiktokUrl": "https://www.tiktok.com/@lapegatinaband",
    "xUrl": "https://x.com/lapegatina"
  },
  "dubiozakolektiv": {
    "officialWebsite": "https://dubioza.org",
    "tiktokUrl": "https://www.tiktok.com/@dubiozakolektiv",
    "xUrl": "https://x.com/dubiozakolektiv"
  },
  "boikot": {
    "officialWebsite": "https://boikot.com.es",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/boikotoficial"
  },
  "segismundotoxicomano": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "defcondos": {
    "officialWebsite": "https://defcondos.com",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/def_con_dos"
  },
  "losdemarras": {
    "officialWebsite": "https://losdemarras.es",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/losdemarras"
  },
  "markyramonesblitzkrieg": {
    "officialWebsite": "https://markyramone.com",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/markyramone"
  },
  "trashtucada": {
    "officialWebsite": "https://trashtucada.com",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/trashtucada"
  },
  "kamikazes": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "mefritosandthegimmecheetos": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "mamaladilla": {
    "officialWebsite": "https://mamaladilla.com",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "aguabendita": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "skaparapid": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "crim": {
    "officialWebsite": "https://crim.cat",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/crimpunk"
  },
  "kantepinreliko": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "https://x.com/Kante_Pinrelico"
  },
  "sinpropina": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "avancarga": {
    "officialWebsite": "124",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "4dziki": {
    "officialWebsite": "https://4dziki.pl",
    "tiktokUrl": "124",
    "xUrl": "124"
  },
  "airos": {
    "officialWebsite": "https://www.aerosmith.com/",
    "tiktokUrl": "https://www.tiktok.com/@aerosmith",
    "xUrl": "https://x.com/Aerosmith"
  },
  "siddharta": {
    "officialWebsite": "",
    "tiktokUrl": "https://www.tiktok.com/@siddhartha_oficial",
    "xUrl": "https://x.com/iamsiddhartha"
  },
  "eivor": {
    "officialWebsite": "https://www.eivor.com",
    "tiktokUrl": "",
    "xUrl": "https://x.com/eivormusic"
  },
  "allformetal": {
    "officialWebsite": "https://www.allformetal.com/",
    "tiktokUrl": "https://www.tiktok.com/@_allformetal_",
    "xUrl": ""
  },
  "destruction": {
    "officialWebsite": "https://www.destruction.de/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/destruction"
  },
  "lordi": {
    "officialWebsite": "https://lordi.fi",
    "tiktokUrl": "",
    "xUrl": "https://x.com/lordiofficial"
  },
  "calvalouise": {
    "officialWebsite": "https://www.musicglue.com/calvalouise/",
    "tiktokUrl": "",
    "xUrl": "https://twitter.com/calvalouise"
  },
  "primalfear": {
    "officialWebsite": "http://www.primalfear.de/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/Matsinner1"
  },
  "avantasia": {
    "officialWebsite": "https://avantasia.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/_avantasia"
  },
  "soen": {
    "officialWebsite": "http://soenmusic.com/",
    "tiktokUrl": "",
    "xUrl": "https://x.com/soenmusic"
  }
};

function normalizeArtistName(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

export function getArtistSocialLinks(name: string): ArtistSocialLinks {
  return artistSocialLinks[normalizeArtistName(name)] || {};
}
